name: Branch Naming Validation

on:
  push:
    branches:
      - "*" # 모든 브랜치에서 트리거
  pull_request:
    branches:
      - "*" # 모든 풀 리퀘스트 이벤트에서 트리거

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Branch Name
        run: |
          # pull_request 이벤트인 경우, PR의 출발 브랜치 이름은 github.event.pull_request.head.ref에 있음.
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          else
            # push 이벤트인 경우, GITHUB_REF에서 'refs/heads/' 접두사를 제거하여 실제 브랜치 이름을 추출함.
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
          fi
          echo "Current branch: $BRANCH_NAME"
          # 이후 단계에서 사용할 수 있도록 환경변수에 저장
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Validate Branch Name
        if: >
          (github.event_name == 'push' && github.ref != 'refs/heads/main') ||
          (github.event_name == 'pull_request' && github.event.pull_request.base.ref != 'main')
        run: |
          echo "Validating branch name..."
          # 브랜치 이름은 'feature/', 'hotfix/', 'bugfix/' 중 하나로 시작해야 함.
          if [[ ! "$BRANCH_NAME" =~ ^(feature|hotfix|bugfix)/.+ ]]; then
            echo "Branch name '$BRANCH_NAME' does not conform to the required pattern. Example: feature/XXX"
            exit 1
          fi
          echo "Branch name is valid."
